
//! Autogenerated weights for `pallet_digifall`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 59.0.0
//! DATE: 2026-09-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// /tmp/digifall-frame-bencher/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// chain/target/release/wbuild/digifall-template-runtime/digifall_template_runtime.compact.compressed.wasm
// --pallet
// pallet_digifall
// --extrinsic
// *
// --output
// /tmp/digifall-benchmark-full

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_digifall`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_digifall::WeightInfo for WeightInfo<T> {
	/// Storage: `Digifall::Games` (r:1 w:0)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn check_nonce_for_feeless() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `471`
		//  Estimated: `3737`
		// Minimum execution time: 10_336_000 picoseconds.
		Weight::from_parts(12_362_000, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Digifall::ScheduledReveals` (r:1 w:1)
	/// Proof: `Digifall::ScheduledReveals` (`max_values`: None, `max_size`: Some(4022), added: 6497, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::Games` (r:100 w:100)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::RandomMaterial` (r:1 w:0)
	/// Proof: `Randomness::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 100]`.
	fn on_initialize(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85 + r * (166 ±0)`
		//  Estimated: `7487 + r * (2747 ±0)`
		// Minimum execution time: 17_670_000 picoseconds.
		Weight::from_parts(12_187_029, 0)
			.saturating_add(Weight::from_parts(0, 7487))
			// Standard Error: 19_980
			.saturating_add(Weight::from_parts(9_060_300, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2747).saturating_mul(r.into()))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::CurrentStakeBounds` (r:1 w:0)
	/// Proof: `Digifall::CurrentStakeBounds` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::NextGameIds` (r:1 w:1)
	/// Proof: `Digifall::NextGameIds` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::ScheduledReveals` (r:1 w:1)
	/// Proof: `Digifall::ScheduledReveals` (`max_values`: None, `max_size`: Some(4022), added: 6497, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn commit_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `7487`
		// Minimum execution time: 77_944_000 picoseconds.
		Weight::from_parts(100_014_000, 0)
			.saturating_add(Weight::from_parts(0, 7487))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 64]`.
	fn activate_game(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `3737`
		// Minimum execution time: 35_689_000 picoseconds.
		Weight::from_parts(70_509_808, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn resolution_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `491`
		//  Estimated: `3737`
		// Minimum execution time: 31_010_000 picoseconds.
		Weight::from_parts(57_270_000, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn resolution_step_groups() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `491`
		//  Estimated: `3737`
		// Minimum execution time: 28_565_000 picoseconds.
		Weight::from_parts(53_989_000, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 64]`.
	fn play(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `471`
		//  Estimated: `3737`
		// Minimum execution time: 26_400_000 picoseconds.
		Weight::from_parts(41_469_127, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			// Standard Error: 3_645
			.saturating_add(Weight::from_parts(22_646, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn play_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `841`
		//  Estimated: `3737`
		// Minimum execution time: 68_515_000 picoseconds.
		Weight::from_parts(93_450_000, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn play_fault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `702`
		//  Estimated: `6196`
		// Minimum execution time: 88_630_000 picoseconds.
		Weight::from_parts(109_653_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:0)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 64]`.
	fn advance(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `471`
		//  Estimated: `3737`
		// Minimum execution time: 23_327_000 picoseconds.
		Weight::from_parts(33_508_715, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn advance_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `861`
		//  Estimated: `3737`
		// Minimum execution time: 65_791_000 picoseconds.
		Weight::from_parts(84_510_000, 0)
			.saturating_add(Weight::from_parts(0, 3737))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn advance_fault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `722`
		//  Estimated: `6196`
		// Minimum execution time: 88_770_000 picoseconds.
		Weight::from_parts(116_707_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:1 w:2)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn rotate_session() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `573`
		//  Estimated: `6196`
		// Minimum execution time: 38_413_000 picoseconds.
		Weight::from_parts(48_610_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::ScheduledReveals` (r:1 w:1)
	/// Proof: `Digifall::ScheduledReveals` (`max_values`: None, `max_size`: Some(4022), added: 6497, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:0 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn forfeit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4409`
		//  Estimated: `7487`
		// Minimum execution time: 38_484_000 picoseconds.
		Weight::from_parts(47_004_000, 0)
			.saturating_add(Weight::from_parts(0, 7487))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Digifall::Games` (r:1 w:1)
	/// Proof: `Digifall::Games` (`max_values`: None, `max_size`: Some(272), added: 2747, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::ScheduledReveals` (r:1 w:1)
	/// Proof: `Digifall::ScheduledReveals` (`max_values`: None, `max_size`: Some(4022), added: 6497, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::TotalEscrowed` (r:1 w:1)
	/// Proof: `Digifall::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::LastResults` (r:0 w:1)
	/// Proof: `Digifall::LastResults` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Digifall::SessionOwners` (r:0 w:1)
	/// Proof: `Digifall::SessionOwners` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn cancel_pending() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4512`
		//  Estimated: `7487`
		// Minimum execution time: 87_652_000 picoseconds.
		Weight::from_parts(103_018_000, 0)
			.saturating_add(Weight::from_parts(0, 7487))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Digifall::CurrentStakeBounds` (r:0 w:1)
	/// Proof: `Digifall::CurrentStakeBounds` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_stake_bounds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_543_000 picoseconds.
		Weight::from_parts(10_057_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
